### ISSUE TITLE
extractMessages should remove obsolete translations

### ISSUE THREAD

**Issue by bravo-kernel** [langpavel/react-starter-kit#4]
Running `npm run extractMessages` does not remove obsolete ids from the translation files.

**Comment by langpavel** [comment]
If there is non-empty `message`, translation will not be removed automatically. This is desired behavior which prevent information lost.

**Comment by bravo-kernel** [comment]
Without arguing about information being lost/not-lost (git?) there really should be an option to prevent the translation files filling up with orphaned messages. Maybe add a ``--purge` option?

**Comment by langpavel** [comment]
Yes, this is reasonable.

**Comment by bravo-kernel** [comment]
👍

**Comment by langpavel** [comment]
Ok, this is very old issue, so I lost track of what this originally requested..
