### ISSUE TITLE
Can you build project from react-starter-kit with redux, bootstrap and react-route

### ISSUE THREAD

**Issue by namthang** [langpavel/react-starter-kit#5]
Hi author.
Thanks for you code. Best with me. Sorry, my English not good :) 
I see you have react-starter-kit with redux and react-starter-kit with bootstrap and react-route
Can you build project from react-starter-kit with redux, bootstrap and react-route
Thanks so much.

**Comment by langpavel** [comment]
Hi, most is merged to feature branches on upstream: https://github.com/kriasoft/react-starter-kit
